name: niimbot_b1
description: Minimal Flutter app to connect to a NIIMBOT B1 over BLE and print a test label.
publish_to: "none"
version: 2.0.0+10

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  niim_blue_flutter: ^1.0.1
  flutter_blue_plus: ^1.36.8
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
